import type { Metadata } from 'next';

import { ClientWrapper } from '@/common/components/layout/ClientWrapper';
import { Footer } from '@/common/components/layout/footer/Footer';
import Footermobile from '@/common/components/layout/footer/Footermobile';
import { Header } from '@/common/components/layout/header/Header';
import { barlow, boston, geistMono, geistSans, inter } from '@/common/styles/fonts/config';
import { auth } from '@auth';
import '@common/styles/globals.css';
import { SessionProvider } from 'next-auth/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="es" suppressHydrationWarning>
        <body
          className={`${boston.className} ${geistSans.variable} ${barlow.variable} ${inter.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
        >
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
          <Footermobile />
          <ClientWrapper />
        </body>
      </html>
    </SessionProvider>
  );
}
