import type { Metadata } from 'next';

import { Footer } from '@/common/components/layout/Footer';
import { Header } from '@/common/components/layout/header/Header';
import { barlow, boston, geistMono, geistSans, inter } from '@/common/styles/fonts/config';
import { SidebarCart } from '@/modules/cart/components/cart-sidebar/SidebarCart';
import '@common/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${boston.className} ${geistSans.variable} ${barlow.variable} ${inter.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <Header />
        <main className="flex-1">{children}</main>
        <SidebarCart />
        <Footer />
      </body>
    </html>
  );
}
