import type { Metadata } from 'next';

import { ClientWrapper } from '@/common/components/layout/ClientWrapper';
import { Footer } from '@/common/components/layout/footer/Footer';
import Footermobile from '@/common/components/layout/footer/Footermobile';
import { Header } from '@/common/components/layout/header/Header';
import AuthInitializer from '@/common/hooks/useAuthInitializer';
import { barlow, boston, geistMono, geistSans, inter } from '@/common/styles/fonts/config';
import { AUTH_COOKIE_NAME } from '@/config/env.config';
import '@common/styles/globals.css';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();

  const hasAuthCookie = cookieStore.has(AUTH_COOKIE_NAME);
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={`${boston.className} ${geistSans.variable} ${barlow.variable} ${inter.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
      >
        <Header />
        <AuthInitializer shouldFetch={hasAuthCookie} />

        <main className="flex-1">{children}</main>
        <Footer />
        <Footermobile />
        <ClientWrapper />
      </body>
    </html>
  );
}
